In [3]:
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

PROJECT_ROOT = Path.cwd().parent
DATA_PATH = PROJECT_ROOT / "data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv"

df = pd.read_csv(
    PROJECT_ROOT / "data/processed/telco_churn_clean.csv"
)

X = df.drop(columns=["Churn", "customerID"])
y = df["Churn"].map({"No": 0, "Yes": 1})

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [5]:
categorical_cols = X.select_dtypes(include="object").columns
numeric_cols = X.select_dtypes(exclude="object").columns

C:\Users\Abhishek Vishwakarma\AppData\Local\Temp\ipykernel_18368\3906763163.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X.select_dtypes(include="object").columns

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

preprocessor = ColumnTransformer([
    ("num", StandardScaler(), numeric_cols),
    ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
])

In [7]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

baseline_model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(max_iter=1000))
])

baseline_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='str')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='str'))])),
                ('classifier', LogisticRegression(max_iter=1000))])

In [8]:
from sklearn.metrics import classification_report, roc_auc_score

pred = baseline_model.predict(X_test)
prob = baseline_model.predict_proba(X_test)[:, 1]

print(classification_report(y_test, pred))
print("ROC-AUC:", roc_auc_score(y_test, prob))

              precision    recall  f1-score   support

           0       0.85      0.89      0.87      1033
           1       0.65      0.57      0.61       374

    accuracy                           0.80      1407
   macro avg       0.75      0.73      0.74      1407
weighted avg       0.80      0.80      0.80      1407

ROC-AUC: 0.8359290473207676

In [9]:
from sklearn.ensemble import RandomForestClassifier

rf_model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=300,
        random_state=42,
        class_weight="balanced"
    ))
])

rf_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='str')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='str'))])),
                ('classifier',
                 RandomForestClassifier(class_weight='balanced',
                                        n_estimators=300, random_state=42))])

In [10]:
pip install xgboost

Collecting xgboost
  Obtaining dependency information for xgboost from https://files.pythonhosted.org/packages/1f/3d/1661dd114a914a67e3f7ab66fa1382e7599c2a8c340f314ad30a3e2b4d08/xgboost-3.2.0-py3-none-win_amd64.whl.metadata
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in d:\projects\customer-churn-intelligence\.venv\lib\site-packages (from xgboost) (2.4.6)
Requirement already satisfied: scipy in d:\projects\customer-churn-intelligence\.venv\lib\site-packages (from xgboost) (1.17.1)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB 660.6 kB/s eta 0:02:34
   ---------------------------------------- 0.1/101.7 MB 1.6 MB/s eta 0:01:03
   ---------------------------------------- 0.2/101.7 MB 1.6 MB/s eta 0:01:02
   ---------------------------------------- 0.4/101.7 MB 2.3 MB/s eta 0:00:44
   ---------------------------------------- 0.5/101.7 MB 2.4 MB/s eta 0:00:43
   ---------------------------------------- 0.5/101.7 MB 2.4 MB/s eta 0:00:43
   ---------------------------------------- 0.6/101.7 MB 1.8 MB/s eta 0:00:57
   ---------------------------------------- 0.8/101.7 MB 2.3 MB/s eta 0:00:44
   ---------------------------------------- 1.0/101.7 MB 2.3 MB/s eta 0:00:43
   ---------------------------------------- 1.0/101.7 MB 2.5 MB/s eta 0:00:42
   ---------------------------------------- 1.0/101.7 MB 2.5 MB/s eta 0:00:42
   ---------------------------------------- 1.0/101.7 MB 2.5 MB/s eta 0:00:42
   ---------------------------------------- 1.2/101.7 MB 2.0 MB/s eta 0:00:51
    --------------------------------------- 1.4/101.7 MB 2.1 MB/s eta 0:00:48
    --------------------------------------- 1.5/101.7 MB 2.1 MB/s eta 0:00:47
    --------------------------------------- 1.6/101.7 MB 2.2 MB/s eta 0:00:46
    --------------------------------------- 1.8/101.7 MB 2.2 MB/s eta 0:00:45
    --------------------------------------- 1.9/101.7 MB 2.3 MB/s eta 0:00:44
    --------------------------------------- 2.0/101.7 MB 2.3 MB/s eta 0:00:43
    --------------------------------------- 2.2/101.7 MB 2.3 MB/s eta 0:00:43
    --------------------------------------- 2.4/101.7 MB 2.4 MB/s eta 0:00:42
    --------------------------------------- 2.5/101.7 MB 2.5 MB/s eta 0:00:40
   - -------------------------------------- 2.7/101.7 MB 2.5 MB/s eta 0:00:40
   - -------------------------------------- 2.8/101.7 MB 2.6 MB/s eta 0:00:39
   - -------------------------------------- 3.0/101.7 MB 2.6 MB/s eta 0:00:39
   - -------------------------------------- 3.2/101.7 MB 2.6 MB/s eta 0:00:38
   - -------------------------------------- 3.3/101.7 MB 2.6 MB/s eta 0:00:38
   - -------------------------------------- 3.4/101.7 MB 2.6 MB/s eta 0:00:38
   - -------------------------------------- 3.6/101.7 MB 2.7 MB/s eta 0:00:37
   - -------------------------------------- 3.8/101.7 MB 2.7 MB/s eta 0:00:36
   - -------------------------------------- 4.1/101.7 MB 2.8 MB/s eta 0:00:35
   - -------------------------------------- 4.2/101.7 MB 2.8 MB/s eta 0:00:35
   - -------------------------------------- 4.2/101.7 MB 2.8 MB/s eta 0:00:35
   - -------------------------------------- 4.2/101.7 MB 2.8 MB/s eta 0:00:35
   - -------------------------------------- 4.3/101.7 MB 2.7 MB/s eta 0:00:37
   - -------------------------------------- 4.5/101.7 MB 2.7 MB/s eta 0:00:37
   - -------------------------------------- 4.7/101.7 MB 2.7 MB/s eta 0:00:36
   - -------------------------------------- 4.8/101.7 MB 2.7 MB/s eta 0:00:36
   - -------------------------------------- 5.0/101.7 MB 2.8 MB/s eta 0:00:36
   -- ------------------------------------- 5.1/101.7 MB 2.8 MB/s eta 0:00:35
   -- ------------------------------------- 5.4/101.7 MB 2.8 MB/s eta 0:00:35
   -- ------------------------------------- 5.5/101.7 MB 2.8 MB/s eta 0:00:35
   -- ------------------------------------- 5.7/101.7 MB 2.8 MB/s eta 0:00:34
   -- ------------------------------------- 5.8/101.7 MB 2.9 MB/s eta 0:00:34
   -- ------------------------------------- 6.1/101.7 MB 2.9 MB/s eta 0:00:33
   -- ------------------------------------- 6.3/101.7 MB 2.9 MB/s eta 0:00:33
   -- ------------------------------------- 6.5/101.7 MB 3.0 MB/s eta 0:00:33
   -- ------------------------------------- 6.7/101.7 MB 3.0 MB/s eta 0:00:32
   -- ------------------------------------- 6.9/101.7 MB 3.0 MB/s eta 0:00:32
   -- ------------------------------------- 7.2/101.7 MB 3.1 MB/s eta 0:00:31
   -- ------------------------------------- 7.4/101.7 MB 3.1 MB/s eta 0:00:31
   --- ------------------------------------ 7.7/101.7 MB 3.2 MB/s eta 0:00:30
   --- ------------------------------------ 7.9/101.7 MB 3.2 MB/s eta 0:00:30
   --- ------------------------------------ 8.2/101.7 MB 3.2 MB/s eta 0:00:29
   --- ------------------------------------ 8.4/101.7 MB 3.3 MB/s eta 0:00:29
   --- ------------------------------------ 8.6/101.7 MB 3.3 MB/s eta 0:00:29
   --- ------------------------------------ 8.9/101.7 MB 3.3 MB/s eta 0:00:28
   --- ------------------------------------ 9.1/101.7 MB 3.4 MB/s eta 0:00:28
   --- ------------------------------------ 9.4/101.7 MB 3.4 MB/s eta 0:00:27
   --- ------------------------------------ 9.6/101.7 MB 3.4 MB/s eta 0:00:28
   --- ------------------------------------ 9.8/101.7 MB 3.4 MB/s eta 0:00:27
   --- ------------------------------------ 9.9/101.7 MB 3.4 MB/s eta 0:00:27
   --- ------------------------------------ 10.1/101.7 MB 3.4 MB/s eta 0:00:27
   --- ------------------------------------ 10.2/101.7 MB 3.4 MB/s eta 0:00:27
   ---- ----------------------------------- 10.3/101.7 MB 3.4 MB/s eta 0:00:27
   ---- ----------------------------------- 10.4/101.7 MB 3.4 MB/s eta 0:00:27
   ---- ----------------------------------- 10.5/101.7 MB 3.4 MB/s eta 0:00:27
   ---- ----------------------------------- 10.7/101.7 MB 3.4 MB/s eta 0:00:27
   ---- ----------------------------------- 10.8/101.7 MB 3.5 MB/s eta 0:00:26
   ---- ----------------------------------- 11.0/101.7 MB 3.5 MB/s eta 0:00:27
   ---- ----------------------------------- 11.0/101.7 MB 3.5 MB/s eta 0:00:27
   ---- ----------------------------------- 11.0/101.7 MB 3.5 MB/s eta 0:00:27
   ---- ----------------------------------- 11.0/101.7 MB 3.5 MB/s eta 0:00:27
   ---- ----------------------------------- 11.0/101.7 MB 3.5 MB/s eta 0:00:27
   ---- ----------------------------------- 11.0/101.7 MB 3.5 MB/s eta 0:00:27
   ---- ----------------------------------- 11.0/101.7 MB 3.5 MB/s eta 0:00:27
   ---- ----------------------------------- 11.1/101.7 MB 3.2 MB/s eta 0:00:29
   ---- ----------------------------------- 11.2/101.7 MB 3.2 MB/s eta 0:00:29
   ---- ----------------------------------- 11.3/101.7 MB 3.3 MB/s eta 0:00:28
   ---- ----------------------------------- 11.4/101.7 MB 3.3 MB/s eta 0:00:28
   ---- ----------------------------------- 11.5/101.7 MB 3.2 MB/s eta 0:00:28
   ---- ----------------------------------- 11.7/101.7 MB 3.3 MB/s eta 0:00:28
   ---- ----------------------------------- 11.8/101.7 MB 3.2 MB/s eta 0:00:28
   ---- ----------------------------------- 12.0/101.7 MB 3.2 MB/s eta 0:00:28
   ---- ----------------------------------- 12.1/101.7 MB 3.3 MB/s eta 0:00:28
   ---- ----------------------------------- 12.2/101.7 MB 3.3 MB/s eta 0:00:28
   ---- ----------------------------------- 12.3/101.7 MB 3.2 MB/s eta 0:00:28
   ---- ----------------------------------- 12.4/101.7 MB 3.2 MB/s eta 0:00:28
   ---- ----------------------------------- 12.5/101.7 MB 3.2 MB/s eta 0:00:28
   ---- ----------------------------------- 12.7/101.7 MB 3.2 MB/s eta 0:00:29
   ----- ---------------------------------- 12.8/101.7 MB 3.2 MB/s eta 0:00:29
   ----- ---------------------------------- 13.0/101.7 MB 3.2 MB/s eta 0:00:28
   ----- ---------------------------------- 13.1/101.7 MB 3.2 MB/s eta 0:00:28
   ----- ---------------------------------- 13.3/101.7 MB 3.2 MB/s eta 0:00:28
   ----- ---------------------------------- 13.4/101.7 MB 3.2 MB/s eta 0:00:28
   ----- ---------------------------------- 13.6/101.7 MB 3.2 MB/s eta 0:00:28
   ----- ---------------------------------- 13.7/101.7 MB 3.2 MB/s eta 0:00:28
   ----- ---------------------------------- 13.9/101.7 MB 3.2 MB/s eta 0:00:28
   ----- ---------------------------------- 14.0/101.7 MB 3.2 MB/s eta 0:00:28
   ----- ---------------------------------- 14.2/101.7 MB 3.1 MB/s eta 0:00:28
   ----- ---------------------------------- 14.3/101.7 MB 3.1 MB/s eta 0:00:28
   ----- ---------------------------------- 14.5/101.7 MB 3.3 MB/s eta 0:00:27
   ----- ---------------------------------- 14.6/101.7 MB 3.2 MB/s eta 0:00:27
   ----- ---------------------------------- 14.7/101.7 MB 3.2 MB/s eta 0:00:27
   ----- ---------------------------------- 14.8/101.7 MB 3.2 MB/s eta 0:00:28
   ----- ---------------------------------- 14.8/101.7 MB 3.2 MB/s eta 0:00:28
   ----- ---------------------------------- 14.8/101.7 MB 3.2 MB/s eta 0:00:28
   ----- ---------------------------------- 14.8/101.7 MB 3.2 MB/s eta 0:00:28
   ----- ---------------------------------- 14.8/101.7 MB 3.2 MB/s eta 0:00:28
   ----- ---------------------------------- 14.8/101.7 MB 3.2 MB/s eta 0:00:28
   ----- ---------------------------------- 14.8/101.7 MB 2.9 MB/s eta 0:00:30
   ----- ---------------------------------- 14.9/101.7 MB 2.9 MB/s eta 0:00:30
   ----- ---------------------------------- 15.0/101.7 MB 2.9 MB/s eta 0:00:30
   ----- ---------------------------------- 15.1/101.7 MB 2.9 MB/s eta 0:00:30
   ------ --------------------------------- 15.3/101.7 MB 2.9 MB/s eta 0:00:30
   ------ --------------------------------- 15.5/101.7 MB 2.9 MB/s eta 0:00:30
   ------ --------------------------------- 15.7/101.7 MB 2.9 MB/s eta 0:00:30
   ------ --------------------------------- 15.8/101.7 MB 2.9 MB/s eta 0:00:30
   ------ --------------------------------- 16.0/101.7 MB 2.9 MB/s eta 0:00:30
   ------ --------------------------------- 16.2/101.7 MB 2.9 MB/s eta 0:00:30
   ------ --------------------------------- 16.4/101.7 MB 2.9 MB/s eta 0:00:30
   ------ --------------------------------- 16.5/101.7 MB 2.9 MB/s eta 0:00:30
   ------ --------------------------------- 16.5/101.7 MB 2.9 MB/s eta 0:00:30
   ------ --------------------------------- 16.5/101.7 MB 2.9 MB/s eta 0:00:30
   ------ --------------------------------- 16.5/101.7 MB 2.9 MB/s eta 0:00:30
   ------ --------------------------------- 16.5/101.7 MB 2.9 MB/s eta 0:00:30
   ------ --------------------------------- 16.5/101.7 MB 2.9 MB/s eta 0:00:30
   ------ --------------------------------- 16.5/101.7 MB 2.9 MB/s eta 0:00:30
   ------ --------------------------------- 16.5/101.7 MB 2.9 MB/s eta 0:00:30
   ------ --------------------------------- 16.5/101.7 MB 2.9 MB/s eta 0:00:30
   ------ --------------------------------- 16.5/101.7 MB 2.9 MB/s eta 0:00:30
   ------ --------------------------------- 16.5/101.7 MB 2.9 MB/s eta 0:00:30
   ------ --------------------------------- 16.5/101.7 MB 2.9 MB/s eta 0:00:30
   ------ --------------------------------- 16.5/101.7 MB 2.9 MB/s eta 0:00:30
   ------ --------------------------------- 16.6/101.7 MB 2.5 MB/s eta 0:00:35
   ------ --------------------------------- 16.6/101.7 MB 2.5 MB/s eta 0:00:35
   ------ --------------------------------- 16.6/101.7 MB 2.4 MB/s eta 0:00:36
   ------ --------------------------------- 16.6/101.7 MB 2.4 MB/s eta 0:00:36
   ------ --------------------------------- 16.8/101.7 MB 2.4 MB/s eta 0:00:36
   ------ --------------------------------- 16.9/101.7 MB 2.4 MB/s eta 0:00:36
   ------ --------------------------------- 17.1/101.7 MB 2.4 MB/s eta 0:00:36
   ------ --------------------------------- 17.2/101.7 MB 2.3 MB/s eta 0:00:36
   ------ --------------------------------- 17.3/101.7 MB 2.3 MB/s eta 0:00:37
   ------ --------------------------------- 17.4/101.7 MB 2.3 MB/s eta 0:00:37
   ------ --------------------------------- 17.6/101.7 MB 2.3 MB/s eta 0:00:37
   ------ --------------------------------- 17.7/101.7 MB 2.3 MB/s eta 0:00:37
   ------ --------------------------------- 17.8/101.7 MB 2.3 MB/s eta 0:00:37
   ------- -------------------------------- 17.8/101.7 MB 2.3 MB/s eta 0:00:38
   ------- -------------------------------- 17.9/101.7 MB 2.2 MB/s eta 0:00:38
   ------- -------------------------------- 18.0/101.7 MB 2.2 MB/s eta 0:00:38
   ------- -------------------------------- 18.1/101.7 MB 2.2 MB/s eta 0:00:38
   ------- -------------------------------- 18.3/101.7 MB 2.2 MB/s eta 0:00:38
   ------- -------------------------------- 18.4/101.7 MB 2.2 MB/s eta 0:00:38
   ------- -------------------------------- 18.6/101.7 MB 2.2 MB/s eta 0:00:38
   ------- -------------------------------- 18.7/101.7 MB 2.2 MB/s eta 0:00:38
   ------- -------------------------------- 18.8/101.7 MB 2.2 MB/s eta 0:00:39
   ------- -------------------------------- 18.9/101.7 MB 2.2 MB/s eta 0:00:39
   ------- -------------------------------- 19.0/101.7 MB 2.1 MB/s eta 0:00:39
   ------- -------------------------------- 19.1/101.7 MB 2.1 MB/s eta 0:00:39
   ------- -------------------------------- 19.2/101.7 MB 2.1 MB/s eta 0:00:39
   ------- -------------------------------- 19.3/101.7 MB 2.1 MB/s eta 0:00:39
   ------- -------------------------------- 19.4/101.7 MB 2.1 MB/s eta 0:00:40
   ------- -------------------------------- 19.6/101.7 MB 2.1 MB/s eta 0:00:40
   ------- -------------------------------- 19.7/101.7 MB 2.1 MB/s eta 0:00:40
   ------- -------------------------------- 19.8/101.7 MB 2.1 MB/s eta 0:00:40
   ------- -------------------------------- 19.9/101.7 MB 2.1 MB/s eta 0:00:40
   ------- -------------------------------- 20.1/101.7 MB 2.1 MB/s eta 0:00:40
   ------- -------------------------------- 20.3/101.7 MB 2.1 MB/s eta 0:00:40
   -------- ------------------------------- 20.4/101.7 MB 2.1 MB/s eta 0:00:39
   -------- ------------------------------- 20.6/101.7 MB 2.1 MB/s eta 0:00:39
   -------- ------------------------------- 20.8/101.7 MB 2.1 MB/s eta 0:00:39
   -------- ------------------------------- 21.0/101.7 MB 2.1 MB/s eta 0:00:39
   -------- ------------------------------- 21.2/101.7 MB 2.1 MB/s eta 0:00:38
   -------- ------------------------------- 21.4/101.7 MB 2.3 MB/s eta 0:00:36
   -------- ------------------------------- 21.5/101.7 MB 2.3 MB/s eta 0:00:36
   -------- ------------------------------- 21.7/101.7 MB 2.3 MB/s eta 0:00:36
   -------- ------------------------------- 21.7/101.7 MB 2.3 MB/s eta 0:00:36
   -------- ------------------------------- 21.9/101.7 MB 2.3 MB/s eta 0:00:36
   -------- ------------------------------- 22.0/101.7 MB 2.3 MB/s eta 0:00:36
   -------- ------------------------------- 22.2/101.7 MB 2.3 MB/s eta 0:00:35
   -------- ------------------------------- 22.4/101.7 MB 2.3 MB/s eta 0:00:35
   -------- ------------------------------- 22.5/101.7 MB 2.3 MB/s eta 0:00:35
   -------- ------------------------------- 22.7/101.7 MB 2.3 MB/s eta 0:00:35
   -------- ------------------------------- 22.8/101.7 MB 2.3 MB/s eta 0:00:35
   --------- ------------------------------ 23.0/101.7 MB 2.3 MB/s eta 0:00:35
   --------- ------------------------------ 23.1/101.7 MB 2.3 MB/s eta 0:00:34
   --------- ------------------------------ 23.3/101.7 MB 2.3 MB/s eta 0:00:34
   --------- ------------------------------ 23.4/101.7 MB 2.3 MB/s eta 0:00:34
   --------- ------------------------------ 23.6/101.7 MB 2.3 MB/s eta 0:00:34
   --------- ------------------------------ 23.8/101.7 MB 2.3 MB/s eta 0:00:34
   --------- ------------------------------ 24.0/101.7 MB 2.3 MB/s eta 0:00:34
   --------- ------------------------------ 24.2/101.7 MB 2.3 MB/s eta 0:00:34
   --------- ------------------------------ 24.2/101.7 MB 2.3 MB/s eta 0:00:34
   --------- ------------------------------ 24.4/101.7 MB 2.3 MB/s eta 0:00:34
   --------- ------------------------------ 24.6/101.7 MB 2.3 MB/s eta 0:00:34
   --------- ------------------------------ 24.8/101.7 MB 2.3 MB/s eta 0:00:33
   --------- ------------------------------ 25.0/101.7 MB 2.4 MB/s eta 0:00:33
   --------- ------------------------------ 25.1/101.7 MB 2.6 MB/s eta 0:00:30
   --------- ------------------------------ 25.3/101.7 MB 2.6 MB/s eta 0:00:30
   ---------- ----------------------------- 25.6/101.7 MB 2.6 MB/s eta 0:00:30
   ---------- ----------------------------- 25.8/101.7 MB 2.6 MB/s eta 0:00:30
   ---------- ----------------------------- 26.1/101.7 MB 2.6 MB/s eta 0:00:29
   ---------- ----------------------------- 26.4/101.7 MB 2.6 MB/s eta 0:00:29
   ---------- ----------------------------- 26.5/101.7 MB 2.6 MB/s eta 0:00:29
   ---------- ----------------------------- 26.7/101.7 MB 3.1 MB/s eta 0:00:24
   ---------- ----------------------------- 27.0/101.7 MB 3.3 MB/s eta 0:00:23
   ---------- ----------------------------- 27.1/101.7 MB 3.2 MB/s eta 0:00:24
   ---------- ----------------------------- 27.2/101.7 MB 3.3 MB/s eta 0:00:23
   ---------- ----------------------------- 27.4/101.7 MB 3.3 MB/s eta 0:00:23
   ---------- ----------------------------- 27.6/101.7 MB 3.3 MB/s eta 0:00:23
   ---------- ----------------------------- 27.7/101.7 MB 3.3 MB/s eta 0:00:23
   ---------- ----------------------------- 27.8/101.7 MB 3.3 MB/s eta 0:00:23
   ----------- ---------------------------- 28.0/101.7 MB 3.3 MB/s eta 0:00:23
   ----------- ---------------------------- 28.1/101.7 MB 3.4 MB/s eta 0:00:22
   ----------- ---------------------------- 28.3/101.7 MB 3.4 MB/s eta 0:00:22
   ----------- ---------------------------- 28.5/101.7 MB 3.4 MB/s eta 0:00:22
   ----------- ---------------------------- 28.6/101.7 MB 3.4 MB/s eta 0:00:22
   ----------- ---------------------------- 28.7/101.7 MB 3.4 MB/s eta 0:00:22
   ----------- ---------------------------- 28.9/101.7 MB 3.4 MB/s eta 0:00:22
   ----------- ---------------------------- 29.1/101.7 MB 3.4 MB/s eta 0:00:22
   ----------- ---------------------------- 29.3/101.7 MB 3.5 MB/s eta 0:00:21
   ----------- ---------------------------- 29.4/101.7 MB 3.5 MB/s eta 0:00:21
   ----------- ---------------------------- 29.6/101.7 MB 3.6 MB/s eta 0:00:21
   ----------- ---------------------------- 29.8/101.7 MB 3.6 MB/s eta 0:00:20
   ----------- ---------------------------- 30.0/101.7 MB 3.6 MB/s eta 0:00:20
   ----------- ---------------------------- 30.1/101.7 MB 3.6 MB/s eta 0:00:20
   ----------- ---------------------------- 30.3/101.7 MB 3.7 MB/s eta 0:00:20
   ----------- ---------------------------- 30.4/101.7 MB 3.6 MB/s eta 0:00:20
   ------------ --------------------------- 30.7/101.7 MB 3.6 MB/s eta 0:00:20
   ------------ --------------------------- 30.9/101.7 MB 3.7 MB/s eta 0:00:20
   ------------ --------------------------- 30.9/101.7 MB 3.7 MB/s eta 0:00:20
   ------------ --------------------------- 31.0/101.7 MB 3.6 MB/s eta 0:00:20
   ------------ --------------------------- 31.2/101.7 MB 3.6 MB/s eta 0:00:20
   ------------ --------------------------- 31.4/101.7 MB 3.6 MB/s eta 0:00:20
   ------------ --------------------------- 31.5/101.7 MB 3.6 MB/s eta 0:00:20
   ------------ --------------------------- 31.7/101.7 MB 3.6 MB/s eta 0:00:20
   ------------ --------------------------- 31.7/101.7 MB 3.5 MB/s eta 0:00:20
   ------------ --------------------------- 31.9/101.7 MB 3.5 MB/s eta 0:00:20
   ------------ --------------------------- 32.1/101.7 MB 3.6 MB/s eta 0:00:20
   ------------ --------------------------- 32.3/101.7 MB 3.6 MB/s eta 0:00:20
   ------------ --------------------------- 32.5/101.7 MB 3.6 MB/s eta 0:00:20
   ------------ --------------------------- 32.5/101.7 MB 3.6 MB/s eta 0:00:20
   ------------ --------------------------- 32.5/101.7 MB 3.6 MB/s eta 0:00:20
   ------------ --------------------------- 32.7/101.7 MB 3.5 MB/s eta 0:00:20
   ------------ --------------------------- 32.9/101.7 MB 3.5 MB/s eta 0:00:20

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
from xgboost import XGBClassifier

xgb_model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", XGBClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=4,
        random_state=42,
        eval_metric="logloss"
    ))
])

xgb_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='str')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=4, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [12]:
from sklearn.metrics import precision_score, recall_score, f1_score

def evaluate(model, name):
    pred = model.predict(X_test)
    prob = model.predict_proba(X_test)[:, 1]

    return {
        "Model": name,
        "Precision": precision_score(y_test, pred),
        "Recall": recall_score(y_test, pred),
        "F1": f1_score(y_test, pred),
        "ROC-AUC": roc_auc_score(y_test, prob)
    }

In [13]:
results = pd.DataFrame([
    evaluate(baseline_model, "Logistic Regression"),
    evaluate(rf_model, "Random Forest"),
    evaluate(xgb_model, "XGBoost")
])

results

                 Model  Precision    Recall        F1   ROC-AUC
0  Logistic Regression   0.648485  0.572193  0.607955  0.835929
1        Random Forest   0.541387  0.647059  0.589525  0.815362
2              XGBoost   0.611285  0.521390  0.562771  0.834911

In [14]:
best_model = xgb_model

prob = best_model.predict_proba(X_test)[:, 1]

for threshold in [0.30, 0.40, 0.50, 0.60]:
    pred = (prob >= threshold).astype(int)

    print(
        threshold,
        "Precision:", round(precision_score(y_test, pred), 3),
        "Recall:", round(recall_score(y_test, pred), 3),
        "F1:", round(f1_score(y_test, pred), 3)
    )

0.3 Precision: 0.524 Recall: 0.765 F1: 0.622
0.4 Precision: 0.585 Recall: 0.652 F1: 0.617
0.5 Precision: 0.611 Recall: 0.521 F1: 0.563
0.6 Precision: 0.673 Recall: 0.38 F1: 0.485

In [15]:
customer_results = X_test.copy()

customer_results["ActualChurn"] = y_test.values
customer_results["ChurnProbability"] = prob

customer_results["RevenueAtRisk"] = (
    customer_results["ChurnProbability"]
    * customer_results["MonthlyCharges"]
)

In [16]:
customer_results.sort_values(
    "RevenueAtRisk",
    ascending=False
)[
    ["MonthlyCharges", "ChurnProbability", "RevenueAtRisk"]
].head(20)

      MonthlyCharges  ChurnProbability  RevenueAtRisk
3080          105.35          0.894752      94.262095
2792          100.95          0.913255      92.193054
2241          102.45          0.898298      92.030614
3949          105.30          0.872152      91.837621
2626           99.25          0.924748      91.781204
2748           95.65          0.944437      90.335362
3374           95.10          0.949205      90.269428
6828          100.75          0.888418      89.508139
1070           98.05          0.905888      88.822326
3721           96.60          0.906059      87.525342
6231           93.30          0.924698      86.274323
1396           99.80          0.860963      85.924124
3154           94.85          0.901935      85.548544
85             99.30          0.854546      84.856389
383            90.85          0.904426      82.167138
4670           94.20          0.867513      81.719736
1719           94.90          0.859241      81.541994
5218           96.20          0.844137      81.205946
4577           85.05          0.935468      79.561514
4693          104.35          0.751549      78.424126

In [17]:
def risk_level(prob):
    if prob >= 0.70:
        return "High"
    elif prob >= 0.40:
        return "Medium"
    return "Low"

customer_results["RiskLevel"] = (
    customer_results["ChurnProbability"]
    .apply(risk_level)
)

In [18]:
pip install shap

Collecting shap
  Obtaining dependency information for shap from https://files.pythonhosted.org/packages/a5/8e/cee1ee136a4e54fe2fbb63a60d72d7c25e21a4ffe6aa05779cab7669cb31/shap-0.51.0-cp311-cp311-win_amd64.whl.metadata
  Using cached shap-0.51.0-cp311-cp311-win_amd64.whl.metadata (26 kB)
Requirement already satisfied: numpy>=2 in d:\projects\customer-churn-intelligence\.venv\lib\site-packages (from shap) (2.4.6)
Requirement already satisfied: scipy in d:\projects\customer-churn-intelligence\.venv\lib\site-packages (from shap) (1.17.1)
Requirement already satisfied: scikit-learn in d:\projects\customer-churn-intelligence\.venv\lib\site-packages (from shap) (1.9.1)
Requirement already satisfied: pandas in d:\projects\customer-churn-intelligence\.venv\lib\site-packages (from shap) (3.0.6)
Collecting tqdm>=4.27.0 (from shap)
  Obtaining dependency information for tqdm>=4.27.0 from https://files.pythonhosted.org/packages/a7/03/921a3d3c75785aca9ebfbfcabfbc3a1be12e2ab5265deb026d55a5a3f83e/tqdm-4.70.1-py3-none-any.whl.metadata
  Downloading tqdm-4.70.1-py3-none-any.whl.metadata (57 kB)
     ---------------------------------------- 0.0/57.4 kB ? eta -:--:--
     ---------------------------------------- 57.4/57.4 kB 1.0 MB/s eta 0:00:00
Requirement already satisfied: packaging>20.9 in d:\projects\customer-churn-intelligence\.venv\lib\site-packages (from shap) (26.3)
Collecting slicer==0.0.8 (from shap)
  Obtaining dependency information for slicer==0.0.8 from https://files.pythonhosted.org/packages/63/81/9ef641ff4e12cbcca30e54e72fb0951a2ba195d0cda0ba4100e532d929db/slicer-0.0.8-py3-none-any.whl.metadata
  Using cached slicer-0.0.8-py3-none-any.whl.metadata (4.0 kB)
Collecting numba (from shap)
  Obtaining dependency information for numba from https://files.pythonhosted.org/packages/41/0e/369fc577564e07820d5f8ddddf9648cf3e31415313c323cbd611f7905101/numba-0.68.0-cp311-cp311-win_amd64.whl.metadata
  Downloading numba-0.68.0-cp311-cp311-win_amd64.whl.metadata (2.9 kB)
Collecting llvmlite (from shap)
  Obtaining dependency information for llvmlite from https://files.pythonhosted.org/packages/6b/15/db28c1cb84314bdc416f7dbe7688aa9565d36d76c8244a1c8fbf6adf37bf/llvmlite-0.50.0-cp311-cp311-win_amd64.whl.metadata
  Downloading llvmlite-0.50.0-cp311-cp311-win_amd64.whl.metadata (5.0 kB)
Requirement already satisfied: cloudpickle in d:\projects\customer-churn-intelligence\.venv\lib\site-packages (from shap) (3.1.2)
Requirement already satisfied: typing-extensions in d:\projects\customer-churn-intelligence\.venv\lib\site-packages (from shap) (4.16.0)
Requirement already satisfied: colorama in d:\projects\customer-churn-intelligence\.venv\lib\site-packages (from tqdm>=4.27.0->shap) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\projects\customer-churn-intelligence\.venv\lib\site-packages (from pandas->shap) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\projects\customer-churn-intelligence\.venv\lib\site-packages (from pandas->shap) (2026.5)
Requirement already satisfied: joblib>=1.4.0 in d:\projects\customer-churn-intelligence\.venv\lib\site-packages (from scikit-learn->shap) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in d:\projects\customer-churn-intelligence\.venv\lib\site-packages (from scikit-learn->shap) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in d:\projects\customer-churn-intelligence\.venv\lib\site-packages (from scikit-learn->shap) (3.7.0)
Requirement already satisfied: six>=1.5 in d:\projects\customer-churn-intelligence\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas->shap) (1.17.0)
Using cached shap-0.51.0-cp311-cp311-win_amd64.whl (554 kB)
Using cached slicer-0.0.8-py3-none-any.whl (15 kB)
Downloading tqdm-4.70.1-py3-none-any.whl (80 kB)
   ---------------------------------------- 0.0/80.2 kB ? eta -:--:--
   ---------------------------------------- 80.2/80.2 kB 2.3 MB/s eta 0:00:00
Downloading llvmlite-0.50.0-cp311-cp311-win_amd64.whl (41.9 MB)
   ---------------------------------------- 0.0/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB 8.6 MB/s eta 0:00:05
   ---------------------------------------- 0.5/41.9 MB 6.5 MB/s eta 0:00:07
    --------------------------------------- 0.7/41.9 MB 7.2 MB/s eta 0:00:06
    --------------------------------------- 0.8/41.9 MB 4.8 MB/s eta 0:00:09
    --------------------------------------- 0.9/41.9 MB 4.1 MB/s eta 0:00:10
   - -------------------------------------- 1.2/41.9 MB 4.3 MB/s eta 0:00:10
   - -------------------------------------- 1.4/41.9 MB 4.5 MB/s eta 0:00:09
   - -------------------------------------- 1.7/41.9 MB 4.7 MB/s eta 0:00:09
   - -------------------------------------- 1.9/41.9 MB 4.8 MB/s eta 0:00:09
   -- ------------------------------------- 2.1/41.9 MB 4.8 MB/s eta 0:00:09
   -- ------------------------------------- 2.4/41.9 MB 4.8 MB/s eta 0:00:09
   -- ------------------------------------- 2.6/41.9 MB 4.7 MB/s eta 0:00:09
   -- ------------------------------------- 2.8/41.9 MB 4.8 MB/s eta 0:00:09
   -- ------------------------------------- 3.0/41.9 MB 4.6 MB/s eta 0:00:09
   --- ------------------------------------ 3.2/41.9 MB 4.6 MB/s eta 0:00:09
   --- ------------------------------------ 3.4/41.9 MB 4.6 MB/s eta 0:00:09
   --- ------------------------------------ 3.6/41.9 MB 4.6 MB/s eta 0:00:09
   --- ------------------------------------ 3.8/41.9 MB 4.5 MB/s eta 0:00:09
   --- ------------------------------------ 3.9/41.9 MB 4.6 MB/s eta 0:00:09
   --- ------------------------------------ 4.0/41.9 MB 4.3 MB/s eta 0:00:09
   --- ------------------------------------ 4.1/41.9 MB 4.2 MB/s eta 0:00:10
   --- ------------------------------------ 4.2/41.9 MB 4.1 MB/s eta 0:00:10
   ---- ----------------------------------- 4.3/41.9 MB 4.1 MB/s eta 0:00:10
   ---- ----------------------------------- 4.5/41.9 MB 4.1 MB/s eta 0:00:10
   ---- ----------------------------------- 4.6/41.9 MB 4.0 MB/s eta 0:00:10
   ---- ----------------------------------- 4.8/41.9 MB 4.0 MB/s eta 0:00:10
   ---- ----------------------------------- 4.9/41.9 MB 3.9 MB/s eta 0:00:10
   ---- ----------------------------------- 5.1/41.9 MB 3.9 MB/s eta 0:00:10
   ---- ----------------------------------- 5.2/41.9 MB 3.9 MB/s eta 0:00:10
   ----- ---------------------------------- 5.4/41.9 MB 3.9 MB/s eta 0:00:10
   ----- ---------------------------------- 5.5/41.9 MB 3.8 MB/s eta 0:00:10
   ----- ---------------------------------- 5.7/41.9 MB 3.8 MB/s eta 0:00:10
   ----- ---------------------------------- 5.9/41.9 MB 3.8 MB/s eta 0:00:10
   ----- ---------------------------------- 6.1/41.9 MB 3.8 MB/s eta 0:00:10
   ----- ---------------------------------- 6.2/41.9 MB 3.8 MB/s eta 0:00:10
   ------ --------------------------------- 6.4/41.9 MB 3.8 MB/s eta 0:00:10
   ------ --------------------------------- 6.6/41.9 MB 3.8 MB/s eta 0:00:10
   ------ --------------------------------- 6.7/41.9 MB 3.8 MB/s eta 0:00:10
   ------ --------------------------------- 6.9/41.9 MB 3.8 MB/s eta 0:00:10
   ------ --------------------------------- 7.1/41.9 MB 3.8 MB/s eta 0:00:10
   ------ --------------------------------- 7.3/41.9 MB 3.8 MB/s eta 0:00:10
   ------- -------------------------------- 7.5/41.9 MB 3.8 MB/s eta 0:00:09
   ------- -------------------------------- 7.7/41.9 MB 3.8 MB/s eta 0:00:09
   ------- -------------------------------- 7.9/41.9 MB 3.8 MB/s eta 0:00:09
   ------- -------------------------------- 8.1/41.9 MB 3.8 MB/s eta 0:00:09
   ------- -------------------------------- 8.3/41.9 MB 3.9 MB/s eta 0:00:09
   -------- ------------------------------- 8.5/41.9 MB 3.9 MB/s eta 0:00:09
   -------- ------------------------------- 8.7/41.9 MB 3.9 MB/s eta 0:00:09
   -------- ------------------------------- 8.9/41.9 MB 3.9 MB/s eta 0:00:09
   -------- ------------------------------- 9.2/41.9 MB 3.9 MB/s eta 0:00:09
   --------- ------------------------------ 9.4/41.9 MB 3.9 MB/s eta 0:00:09
   --------- ------------------------------ 9.6/41.9 MB 4.0 MB/s eta 0:00:09
   --------- ------------------------------ 9.7/41.9 MB 3.9 MB/s eta 0:00:09
   --------- ------------------------------ 9.8/41.9 MB 3.8 MB/s eta 0:00:09
   --------- ------------------------------ 10.0/41.9 MB 3.9 MB/s eta 0:00:09
   --------- ------------------------------ 10.3/41.9 MB 3.9 MB/s eta 0:00:09
   --------- ------------------------------ 10.4/41.9 MB 3.9 MB/s eta 0:00:09
   ---------- ----------------------------- 10.7/41.9 MB 3.8 MB/s eta 0:00:09
   ---------- ----------------------------- 10.9/41.9 MB 3.8 MB/s eta 0:00:09
   ---------- ----------------------------- 11.1/41.9 MB 3.9 MB/s eta 0:00:08
   ---------- ----------------------------- 11.3/41.9 MB 3.9 MB/s eta 0:00:08
   ----------- ---------------------------- 11.6/41.9 MB 3.9 MB/s eta 0:00:08
   ----------- ---------------------------- 11.8/41.9 MB 3.9 MB/s eta 0:00:08
   ----------- ---------------------------- 12.1/41.9 MB 3.9 MB/s eta 0:00:08
   ----------- ---------------------------- 12.3/41.9 MB 3.9 MB/s eta 0:00:08
   ----------- ---------------------------- 12.5/41.9 MB 3.9 MB/s eta 0:00:08
   ------------ --------------------------- 12.7/41.9 MB 3.9 MB/s eta 0:00:08
   ------------ --------------------------- 13.0/41.9 MB 3.9 MB/s eta 0:00:08
   ------------ --------------------------- 13.2/41.9 MB 3.9 MB/s eta 0:00:08
   ------------ --------------------------- 13.4/41.9 MB 3.9 MB/s eta 0:00:08
   ------------ --------------------------- 13.5/41.9 MB 3.9 MB/s eta 0:00:08
   ------------- -------------------------- 13.7/41.9 MB 3.9 MB/s eta 0:00:08
   ------------- -------------------------- 13.8/41.9 MB 3.9 MB/s eta 0:00:08
   ------------- -------------------------- 13.9/41.9 MB 3.9 MB/s eta 0:00:08
   ------------- -------------------------- 14.1/41.9 MB 3.8 MB/s eta 0:00:08
   ------------- -------------------------- 14.3/41.9 MB 3.9 MB/s eta 0:00:08
   ------------- -------------------------- 14.4/41.9 MB 4.0 MB/s eta 0:00:07
   ------------- -------------------------- 14.6/41.9 MB 4.0 MB/s eta 0:00:07
   -------------- ------------------------- 14.7/41.9 MB 3.9 MB/s eta 0:00:07
   -------------- ------------------------- 15.0/41.9 MB 3.9 MB/s eta 0:00:07
   -------------- ------------------------- 15.2/41.9 MB 4.0 MB/s eta 0:00:07
   -------------- ------------------------- 15.3/41.9 MB 4.0 MB/s eta 0:00:07
   -------------- ------------------------- 15.6/41.9 MB 4.0 MB/s eta 0:00:07
   --------------- ------------------------ 15.8/41.9 MB 4.1 MB/s eta 0:00:07
   --------------- ------------------------ 15.9/41.9 MB 4.1 MB/s eta 0:00:07
   --------------- ------------------------ 16.2/41.9 MB 4.1 MB/s eta 0:00:07
   --------------- ------------------------ 16.4/41.9 MB 4.1 MB/s eta 0:00:07
   --------------- ------------------------ 16.6/41.9 MB 4.2 MB/s eta 0:00:07
   ---------------- ----------------------- 16.8/41.9 MB 4.2 MB/s eta 0:00:07
   ---------------- ----------------------- 17.1/41.9 MB 4.2 MB/s eta 0:00:06
   ---------------- ----------------------- 17.3/41.9 MB 4.2 MB/s eta 0:00:06
   ---------------- ----------------------- 17.6/41.9 MB 4.2 MB/s eta 0:00:06
   ----------------- ---------------------- 17.8/41.9 MB 4.3 MB/s eta 0:00:06
   ----------------- ---------------------- 18.1/41.9 MB 4.3 MB/s eta 0:00:06
   ----------------- ---------------------- 18.3/41.9 MB 4.3 MB/s eta 0:00:06
   ----------------- ---------------------- 18.6/41.9 MB 4.3 MB/s eta 0:00:06
   ----------------- ---------------------- 18.8/41.9 MB 4.3 MB/s eta 0:00:06
   ------------------ --------------------- 19.0/41.9 MB 4.4 MB/s eta 0:00:06
   ------------------ --------------------- 19.2/41.9 MB 4.3 MB/s eta 0:00:06
   ------------------ --------------------- 19.3/41.9 MB 4.3 MB/s eta 0:00:06
   ------------------ --------------------- 19.4/41.9 MB 4.3 MB/s eta 0:00:06
   ------------------ --------------------- 19.5/41.9 MB 4.2 MB/s eta 0:00:06
   ------------------ --------------------- 19.6/41.9 MB 4.1 MB/s eta 0:00:06
   ------------------ --------------------- 19.7/41.9 MB 4.1 MB/s eta 0:00:06
   ------------------- -------------------- 19.9/41.9 MB 4.2 MB/s eta 0:00:06
   ------------------- -------------------- 20.1/41.9 MB 4.2 MB/s eta 0:00:06
   ------------------- -------------------- 20.2/41.9 MB 4.2 MB/s eta 0:00:06
   ------------------- -------------------- 20.3/41.9 MB 4.1 MB/s eta 0:00:06
   ------------------- -------------------- 20.5/41.9 MB 4.1 MB/s eta 0:00:06
   ------------------- -------------------- 20.7/41.9 MB 4.1 MB/s eta 0:00:06
   ------------------- -------------------- 20.9/41.9 MB 4.1 MB/s eta 0:00:06
   -------------------- ------------------- 21.1/41.9 MB 4.1 MB/s eta 0:00:06
   -------------------- ------------------- 21.3/41.9 MB 4.1 MB/s eta 0:00:06
   -------------------- ------------------- 21.5/41.9 MB 4.1 MB/s eta 0:00:05
   -------------------- ------------------- 21.7/41.9 MB 4.1 MB/s eta 0:00:05
   -------------------- ------------------- 21.8/41.9 MB 4.0 MB/s eta 0:00:05
   --------------------- ------------------ 22.0/41.9 MB 4.0 MB/s eta 0:00:05
   --------------------- ------------------ 22.2/41.9 MB 4.0 MB/s eta 0:00:05
   --------------------- ------------------ 22.5/41.9 MB 4.0 MB/s eta 0:00:05
   --------------------- ------------------ 22.7/41.9 MB 4.0 MB/s eta 0:00:05
   --------------------- ------------------ 22.9/41.9 MB 4.0 MB/s eta 0:00:05
   ---------------------- ----------------- 23.1/41.9 MB 4.0 MB/s eta 0:00:05
   ---------------------- ----------------- 23.3/41.9 MB 4.0 MB/s eta 0:00:05
   ---------------------- ----------------- 23.5/41.9 MB 4.0 MB/s eta 0:00:05
   ---------------------- ----------------- 23.6/41.9 MB 3.9 MB/s eta 0:00:05
   ---------------------- ----------------- 23.7/41.9 MB 3.9 MB/s eta 0:00:05
   ---------------------- ----------------- 23.8/41.9 MB 4.0 MB/s eta 0:00:05
   ----------------------- ---------------- 24.1/41.9 MB 4.0 MB/s eta 0:00:05
   ----------------------- ---------------- 24.3/41.9 MB 4.0 MB/s eta 0:00:05
   ----------------------- ---------------- 24.6/41.9 MB 4.1 MB/s eta 0:00:05
   ----------------------- ---------------- 24.8/41.9 MB 4.1 MB/s eta 0:00:05
   ----------------------- ---------------- 25.0/41.9 MB 4.1 MB/s eta 0:00:05
   ------------------------ --------------- 25.2/41.9 MB 4.1 MB/s eta 0:00:05
   ------------------------ --------------- 25.3/41.9 MB 4.1 MB/s eta 0:00:05
   ------------------------ --------------- 25.5/41.9 MB 4.1 MB/s eta 0:00:04
   ------------------------ --------------- 25.7/41.9 MB 4.1 MB/s eta 0:00:04
   ------------------------ --------------- 25.8/41.9 MB 4.1 MB/s eta 0:00:04
   ------------------------ --------------- 26.0/41.9 MB 4.0 MB/s eta 0:00:04
   ------------------------- -------------- 26.2/41.9 MB 4.1 MB/s eta 0:00:04
   ------------------------- -------------- 26.4/41.9 MB 4.1 MB/s eta 0:00:04
   ------------------------- -------------- 26.6/41.9 MB 4.1 MB/s eta 0:00:04
   ------------------------- -------------- 26.8/41.9 MB 4.0 MB/s eta 0:00:04
   ------------------------- -------------- 27.0/41.9 MB 4.0 MB/s eta 0:00:04
   -------------------------- ------------- 27.2/41.9 MB 4.0 MB/s eta 0:00:04
   -------------------------- ------------- 27.3/41.9 MB 4.0 MB/s eta 0:00:04
   -------------------------- ------------- 27.6/41.9 MB 4.0 MB/s eta 0:00:04
   -------------------------- ------------- 27.9/41.9 MB 4.0 MB/s eta 0:00:04
   -------------------------- ------------- 28.0/41.9 MB 4.0 MB/s eta 0:00:04
   --------------------------- ------------ 28.3/41.9 MB 4.0 MB/s eta 0:00:04
   --------------------------- ------------ 28.5/41.9 MB 4.0 MB/s eta 0:00:04
   --------------------------- ------------ 28.7/41.9 MB 3.9 MB/s eta 0:00:04
   --------------------------- ------------ 29.0/41.9 MB 4.0 MB/s eta 0:00:04
   --------------------------- ------------ 29.3/41.9 MB 4.0 MB/s eta 0:00:04
   ---------------------------- ----------- 29.5/41.9 MB 4.1 MB/s eta 0:00:04
   ---------------------------- ----------- 29.5/41.9 MB 4.1 MB/s eta 0:00:04
   ---------------------------- ----------- 29.5/41.9 MB 4.1 MB/s eta 0:00:04
   ---------------------------- ----------- 29.7/41.9 MB 4.0 MB/s eta 0:00:04
   ---------------------------- ----------- 29.9/41.9 MB 4.0 MB/s eta 0:00:03
   ---------------------------- ----------- 30.1/41.9 MB 4.1 MB/s eta 0:00:03
   ---------------------------- ----------- 30.3/41.9 MB 4.1 MB/s eta 0:00:03
   ----------------------------- ---------- 30.5/41.9 MB 4.1 MB/s eta 0:00:03
   ----------------------------- ---------- 30.7/41.9 MB 4.1 MB/s eta 0:00:03
   ----------------------------- ---------- 30.9/41.9 MB 4.1 MB/s eta 0:00:03
   ----------------------------- ---------- 31.1/41.9 MB 4.1 MB/s eta 0:00:03
   ----------------------------- ---------- 31.2/41.9 MB 4.1 MB/s eta 0:00:03
   ------------------------------ --------- 31.4/41.9 MB 4.1 MB/s eta 0:00:03
   ------------------------------ --------- 31.6/41.9 MB 4.1 MB/s eta 0:00:03
   ------------------------------ --------- 31.8/41.9 MB 4.1 MB/s eta 0:00:03
   ------------------------------ --------- 32.0/41.9 MB 4.1 MB/s eta 0:00:03
   ------------------------------ --------- 32.2/41.9 MB 4.1 MB/s eta 0:00:03
   ------------------------------ --------- 32.4/41.9 MB 4.1 MB/s eta 0:00:03
   ------------------------------- -------- 32.7/41.9 MB 4.1 MB/s eta 0:00:03
   ------------------------------- -------- 32.9/41.9 MB 4.1 MB/s eta 0:00:03
   ------------------------------- -------- 33.1/41.9 MB 4.2 MB/s eta 0:00:03
   ------------------------------- -------- 33.4/41.9 MB 4.1 MB/s eta 0:00:03
   -------------------------------- ------- 33.6/41.9 MB 4.2 MB/s eta 0:00:02
   -------------------------------- ------- 33.9/41.9 MB 4.2 MB/s eta 0:00:02
   -------------------------------- ------- 34.1/41.9 MB 4.3 MB/s eta 0:00:02
   -------------------------------- ------- 34.3/41.9 MB 4.3 MB/s eta 0:00:02
   -------------------------------- ------- 34.5/41.9 MB 4.3 MB/s eta 0:00:02
   --------------------------------- ------ 34.8/41.9 MB 4.3 MB/s eta 0:00:02
   --------------------------------- ------ 35.0/41.9 MB 4.3 MB/s eta 0:00:02
   --------------------------------- ------ 35.3/41.9 MB 4.3 MB/s eta 0:00:02
   --------------------------------- ------ 35.5/41.9 MB 4.3 MB/s eta 0:00:02
   ---------------------------------- ----- 35.7/41.9 MB 4.4 MB/s eta 0:00:02
   ---------------------------------- ----- 36.0/41.9 MB 4.5 MB/s eta 0:00:02
   ---------------------------------- ----- 36.2/41.9 MB 4.4 MB/s eta 0:00:02
   ---------------------------------- ----- 36.3/41.9 MB 4.4 MB/s eta 0:00:02
   ---------------------------------- ----- 36.5/41.9 MB 4.4 MB/s eta 0:00:02
   ----------------------------------- ---- 36.7/41.9 MB 4.4 MB/s eta 0:00:02
   ----------------------------------- ---- 36.9/41.9 MB 4.4 MB/s eta 0:00:02
   ----------------------------------- ---- 36.9/41.9 MB 4.4 MB/s eta 0:00:02
   ----------------------------------- ---- 37.1/41.9 MB 4.3 MB/s eta 0:00:02
   ----------------------------------- ---- 37.2/41.9 MB 4.3 MB/s eta 0:00:02
   ----------------------------------- ---- 37.3/41.9 MB 4.2 MB/s eta 0:00:02
   ----------------------------------- ---- 37.3/41.9 MB 4.3 MB/s eta 0:00:02
   ----------------------------------- ---- 37.3/41.9 MB 4.3 MB/s eta 0:00:02
   ----------------------------------- ---- 37.3/41.9 MB 4.3 MB/s eta 0:00:02
   ----------------------------------- ---- 37.3/41.9 MB 4.3 MB/s eta 0:00:02
   ----------------------------------- ---- 37.3/41.9 MB 4.3 MB/s eta 0:00:02
   ----------------------------------- ---- 37.4/41.9 MB 3.9 MB/s eta 0:00:02
   ----------------------------------- ---- 37.5/41.9 MB 3.8 MB/s eta 0:00:02
   ----------------------------------- ---- 37.5/41.9 MB 3.8 MB/s eta 0:00:02
   ----------------------------------- ---- 37.5/41.9 MB 3.7 MB/s eta 0:00:02
   ----------------------------------- ---- 37.5/41.9 MB 3.7 MB/s eta 0:00:02

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip